// module-react/exercices/1-composants/composants-app/src/components/ExerciceA1/index.js
import React from 'react'


function ExerciceA1() {
    const resp1 = 36344.789 + 5422.995432;
    const resp2 = "Bonjour".concat("le Monde");
    const resp3 = 4321 % 1234;
    const resp4 =  (0.000005 > 0.00005) ? "true" : "false";
    const x = 4;
    const y = 19;

    return (
        <div className="ExerciceA1">
            <div>
                <p>Que donne la somme de 36344.789 et 5422.995432 ?</p>
                <p> { resp1  } </p>
            </div>
            <div>
                <p>Que donne la concaténation de "Bonjour" et "le Monde" ?</p>
                <p> { resp2 } </p>
            </div>
            <div>
                <p>Quel est le reste de la division entière de 4321 par 1234 ?</p>
                <p> { resp3 } </p>
            </div>
            <div>
                <p>Est-il vrai que 0.000005 est strictement supérieur à 0.00005 ?</p>
                <p> { resp4 } </p>
            </div>
            <div>
                <p>Que donne l'équation ((3x + 2) - (43x * (9y + 6))) / (2y - 7) si x vaut 4 et y vaut 19. Vous devez donc créer 2 constantes numériques dans la méthode render du composant.</p>
                <p> {((3*x + 2) - (43*x * (9*y + 6))) / (2*y - 7)}</p>
            </div>
        </div>
    );
}

export default ExerciceA1;

// module-angular/exercices/1-expressions/exercices/src/app/exercices/1-expressions/exercice-a1/exercice-a1.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-exercice-a1',
  templateUrl: './exercice-a1.component.html',
  styleUrls: ['./exercice-a1.component.css']
})
export class ExerciceA1Component implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<p>Que donne la somme de 36344.789 et 5422.995432 ?</p>
<p>{{ 36344.789 + 5422.995432}}</p>
<p>donne la concaténation de "Bonjour" et "le Monde" ?</p>
<p>{{"Bonjour" + "le Monde"}}</p>
<p>Quel est le reste de la division entière de 4321 par 1234 ?</p>
<p>{{4321%1234}}</p>
<p>Est-il vrai que 0.000005 est strictement supérieur à 0.00005 ?</p>
<p>{{ 0.000005 > 0.00005}}</p>
<p>Que donne l'équation ((3x + 2) - (43x * (9y + 6))) / (2y - 7) si x vaut 4 et y vaut 19. Vous devez donc créer 2 propriétés numériques dans le composant.</p>
